### ISSUE TITLE
Pip install Archer fails

### ISSUE THREAD

**Issue by johncadengo** [eleme/archer#7]
Here is the error I get when running `$ pip install Archer`,

```
Collecting Archer
  Using cached archer-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4hebhh75/Archer/setup.py", line 5, in <module>
        from archer import __version__
      File "/tmp/pip-build-4hebhh75/Archer/archer/__init__.py", line 5, in <module>
        from .app import Archer
      File "/tmp/pip-build-4hebhh75/Archer/archer/app.py", line 11, in <module>
        from thriftpy.parser import _BaseService
    ImportError: cannot import name '_BaseService'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4hebhh75/Archer/
```

It seems the workaround for me right now is to git clone and run `python setup.py develop`. I'm wondering if this is a known issue or what is the best solution for me?

**Comment by wooparadog** [comment]
Hi, archer stopped working because upstream thriftpy has made an incompatible change. We have hence fixed that problem in the repo, but forgot to push it to pypi.

I just uploaded the 0.4 version, all should work fine now.
